### ISSUE TITLE
trying to use trough comfy manager. followed all steps. doesnt work

### ISSUE THREAD

**Issue by Bri0000** [filipemeneses/comfy_pixelization#3]
ModuleNotFoundError: No module named 'gradio'

**Comment by filipemeneses** [comment]
try `pip install gradio`

**Comment by Bri0000** [comment]
all requirements already satisfied

**Comment by purzbeats** [comment]
> all requirements already satisfied

I'm actually having the same issue, I also tried cloning it in and running the installation script manually, same result.

```
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_pixelization\__init__.py", line 9, in <module>
    from .modules import devices, shared
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_pixelization\modules\shared.py", line 8, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_pixelization module for custom nodes: No module named 'gradio'
```

**Comment by filipemeneses** [comment]
@purzbeats @Bri0000 can you take a look if it's working now?

**Comment by purzbeats** [comment]
Works now!! Thanks!
